"""Initial migration

Revision ID: 80795c802a32
Revises: 
Create Date: 2024-11-24 11:23:41.642248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80795c802a32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operarios_codigo'), 'operarios', ['codigo'], unique=True)
    op.create_index(op.f('ix_operarios_id'), 'operarios', ['id'], unique=False)
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('cantidad_producida', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_produccion_id'), 'ordenes_produccion', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_produccion_numero_orden'), 'ordenes_produccion', ['numero_orden'], unique=True)
    op.create_table('versiones_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('es_oem', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versiones_producto_id'), 'versiones_producto', ['id'], unique=False)
    op.create_table('lotes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=20), nullable=False),
    sa.Column('orden_produccion_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('numero_secuencial', sa.Integer(), nullable=False),
    sa.Column('letra_control', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['ordenes_produccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lote')
    )
    op.create_index(op.f('ix_lotes_produccion_id'), 'lotes_produccion', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=15), nullable=True),
    sa.Column('iccid', sa.String(length=20), nullable=True),
    sa.Column('orden_produccion_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('version_producto_id', sa.Integer(), nullable=True),
    sa.Column('es_oem', sa.Boolean(), nullable=True),
    sa.Column('control_activo', sa.Boolean(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_produccion.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operarios.id'], ),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['ordenes_produccion.id'], ),
    sa.ForeignKeyConstraint(['version_producto_id'], ['versiones_producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_iccid'), 'devices', ['iccid'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_imei'), 'devices', ['imei'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_imei'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_iccid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_lotes_produccion_id'), table_name='lotes_produccion')
    op.drop_table('lotes_produccion')
    op.drop_index(op.f('ix_versiones_producto_id'), table_name='versiones_producto')
    op.drop_table('versiones_producto')
    op.drop_index(op.f('ix_ordenes_produccion_numero_orden'), table_name='ordenes_produccion')
    op.drop_index(op.f('ix_ordenes_produccion_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_index(op.f('ix_operarios_id'), table_name='operarios')
    op.drop_index(op.f('ix_operarios_codigo'), table_name='operarios')
    op.drop_table('operarios')
    # ### end Alembic commands ###
